apiVersion: v1
kind: ConfigMap
metadata:
  name: heapster-config
  namespace: kube-system
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration
    baseCPU: 20m
    cpuPerNode: 0.5m
    baseMemory: 50Mi
    memoryPerNode: 4Mi
