## influxdb image version
## ref: https://hub.docker.com/r/library/influxdb/tags/
image:
  repository: "influxdb"
  tag: "1.7.9-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 450Mi
    cpu: 20m
  limits:
    memory: 800Mi
    cpu: 1800m