kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pd-ssd-retained
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-ssd
  zone: europe-west1-b
  replication-type: none
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pd-standard-retained
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-standard
  zone: europe-west1-b
  replication-type: none