apiVersion: v1
data:
  KUBEIP_LABELKEY: "kubeip"
  KUBEIP_LABELVALUE: "cluster-1"
  KUBEIP_NODEPOOL: "ingress-e2-micro-pool"
  KUBEIP_FORCEASSIGNMENT: "true"
kind: ConfigMap
metadata:
  labels:
    app: kubeip
  name: kubeip-config
  namespace: kube-system
