apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # email: redacted
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: default
spec:
  secretName: grafana-certificate-secret
  dnsNames:
  - grafana.atorma.fi
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influxdb-certificate
  namespace: default
spec:
  secretName: influxdb-certificate-secret
  dnsNames:
  - influxdb.atorma.fi
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
