apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #email: redacted
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudDNS:
            #project: redacted
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: atorma-fi-certificate
  namespace: default
spec:
  secretName: atorma-fi-certificate-secret
  dnsNames:
    - "*.atorma.fi"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
