apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  rules:
    - host: grafana.atorma.fi
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 80
            path: /
  tls:
    - hosts:
        - grafana.atorma.fi
      secretName: grafana-certificate-secret
