apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influxdb-certificate
  namespace: default
spec:
  secretName: influxdb-certificate-secret
  dnsNames:
  - influxdb.atorma.fi
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
