apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: influxdb
  name: influxdb2
  namespace: default
data:
  config.toml: |
    bolt-path = "/var/lib/influxdb2/influxd.bolt"
    engine-path = "/var/lib/influxdb2/engine"
    http-bind-address = ":8086"
    influxql-max-select-buckets = 0
    influxql-max-select-point = 0
    influxql-max-select-series = 0
    pprof-disabled = false
    query-concurrency = 0
    reporting-disabled = false
    storage-cache-max-memory-size = 1073741824
    storage-cache-snapshot-memory-size = 26214400
    storage-cache-snapshot-write-cold-duration = "10m0s"
    storage-compact-full-write-cold-duration = "4h0m0s"
    storage-retention-check-interval = "30m0s"
    storage-shard-precreator-advance-period = "30m0s"
    storage-shard-precreator-check-interval = "10m0s"
