apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: influxdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      tolerations:
        - effect: NoExecute
          key: highmem
          value: "true"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: highmem
                    operator: In
                    values:
                      - "true"
              weight: 1
      initContainers:
        - name: pre-start
          image: busybox
          command: [ 'sh', '-c', 'cp /read-only-config/* /etc/influxdb2/' ]
          volumeMounts:
            - name: read-only-config
              mountPath: /read-only-config
            - name: config
              mountPath: /etc/influxdb2
          resources:
            requests:
              cpu: "0"
              memory: "0"
      containers:
        - name: influxdb
          image: influxdb:2.0.7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
              name: api
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: api
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: api
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 150m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: data
            - mountPath: /etc/influxdb2
              name: config
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: influxdb2
        - name: read-only-config
          configMap:
            name: influxdb2
        - name: config
          emptyDir: {}