# InfluxDB data directories must be chowned to uid:gid 1000:1000 before running this.
# Stop/delete influxdb deployment before running this.
# To follow progress: "kubectl logs -f influxdb2-migration"
apiVersion: v1
kind: Pod
metadata:
  name: influxdb2-migration
  namespace: default
spec:
  containers:
    - name: influxdb
      image: influxdb:2.0.7-alpine
      imagePullPolicy: IfNotPresent
      env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: upgrade
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: <redacted>
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: <redacted>
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: home
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: home-bucket
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/influxdb
          name: data
        - mountPath: /etc/influxdb
          name: config
        - mountPath: /var/lib/influxdb2
          name: data2
        - mountPath: /etc/influxdb2
          name: config2
      resources:
        requests:
          cpu: "0"
          memory: "0"
  restartPolicy: Never
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: influxdb-influxdb
    - configMap:
        defaultMode: 420
        name: influxdb
      name: config
    - name: data2
      persistentVolumeClaim:
        claimName: influxdb2
    - name: config2
      persistentVolumeClaim:
        claimName: influxdb2-config